[workspace]
authors = ["Chin-Yun Yu <chin-yun.yu@qmul.ac.uk>"]
channels = ["https://prefix.dev/conda-forge", "nvidia"]
name = "torch_fftconv"
platforms = ["linux-64", "osx-arm64"]

[dependencies]

[target.linux-64.dependencies]
cuda-version = ">=13.0,<14"
pytorch-gpu = ">=1.8.0,<3"
cuda = { version = ">=13.0,<14", channel = "nvidia" }

[pypi-dependencies]
pytest = ">=9.0.3, <10"
pytest-cov = ">=7.1.0, <8"

[system-requirements]
cuda = "13.0"

[target.osx-arm64.dependencies]
pytorch-cpu = ">=1.8.0,<3"
