[build-system]
requires = ["setuptools>=61","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_fftconv"
version = "1.0.0"
description = "Implementation of 1D, 2D, and 3D FFT convolutions in PyTorch. Much faster than direct convolutions for large kernel sizes"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
  { name = "Chin-Yun Yu", email = "chin-yun.yu@qmul.ac.uk" },
]
dependencies = ["torch>=2.0"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
]
urls = { "Homepage" = "https://github.com/yoyolicoris/torch_fftconv" }

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]
include = ["torch_fftconv"]
